/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NicholasEruba.vgc;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Nicholas
 */
public class LoginEnrollPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginEnrollPanel
     */
    public LoginEnrollPanel() {
        initComponents();
        furtherInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginEnrollGroup = new javax.swing.ButtonGroup();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        enrollTeacherRadioButton = new javax.swing.JRadioButton();
        enrollStudentRadioButton = new javax.swing.JRadioButton();
        selectFacultyCombo = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        loginRadioButton = new javax.swing.JRadioButton();
        selectFacultyLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Login/Enroll"));

        emailLabel.setText("E-mail");

        emailTextField.setText("insert email here");
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        passwordLabel.setText("Password");

        passwordTextField.setText("password");

        enrollTeacherRadioButton.setText("Enroll as teacher");
        enrollTeacherRadioButton.setActionCommand("enroll-as-teacher");
        enrollTeacherRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                enrollTeacherRadioButtonItemStateChanged(evt);
            }
        });

        enrollStudentRadioButton.setText("Enroll as student");
        enrollStudentRadioButton.setActionCommand("enroll-as-student");
        enrollStudentRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                enrollStudentRadioButtonItemStateChanged(evt);
            }
        });

        selectFacultyCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectFacultyCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFacultyComboActionPerformed(evt);
            }
        });

        submitButton.setText("Login");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        loginRadioButton.setText("login");
        loginRadioButton.setActionCommand("generic-login");
        loginRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                loginRadioButtonItemStateChanged(evt);
            }
        });
        loginRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginRadioButtonActionPerformed(evt);
            }
        });

        selectFacultyLabel.setText("Select Faculty");

        lastNameTextField.setText("lastname");

        firstNameTextField.setText("firstname");

        lastNameLabel.setText("Lastname");

        firstNameLabel.setText("Firstname");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(loginRadioButton)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enrollTeacherRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enrollStudentRadioButton))
                            .addComponent(submitButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstNameLabel)
                            .addComponent(lastNameLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(118, 118, 118)
                                    .addComponent(emailLabel))
                                .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(selectFacultyLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectFacultyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectFacultyLabel)
                    .addComponent(selectFacultyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginRadioButton)
                    .addComponent(enrollTeacherRadioButton)
                    .addComponent(enrollStudentRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void selectFacultyComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFacultyComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFacultyComboActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        if (loginEnroll(LoginEnrollGroup.getSelection().getActionCommand(), emailTextField.getText(), passwordTextField.getText())) {
//            switch (MainFrame.db.getUserType()) {
//                case "student":
//                    MainFrame.setPane(new StudentPanel());
//                    break;
//                case "teacher":
//                    MainFrame.setPane(new TeacherFacultyPanel());
//                    break;
//            }
            MainFrame.setPane(new RolesPanel((HashMap) MainFrame.db.getUserType()));
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void loginRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_loginRadioButtonItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            //change submit button  etc
            MainFrame.setLoginState("login-as-any");
            selectFacultyCombo.setVisible(false);
            selectFacultyLabel.setVisible(false);
            firstNameLabel.setVisible(false);
            firstNameTextField.setVisible(false);
            lastNameLabel.setVisible(false);
            lastNameTextField.setVisible(false);
            MainFrame.mainframe.pack();
            submitButton.setText("Login");
        }
    }//GEN-LAST:event_loginRadioButtonItemStateChanged

    private void enrollTeacherRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_enrollTeacherRadioButtonItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            //change submit button  etc
            MainFrame.setLoginState("enroll-as-teacher");
            selectFacultyCombo.setVisible(true);
            selectFacultyLabel.setVisible(true);
            firstNameLabel.setVisible(true);
            firstNameTextField.setVisible(true);
            lastNameLabel.setVisible(true);
            lastNameTextField.setVisible(true);
            MainFrame.mainframe.pack();
            submitButton.setText("Enroll as Teacher");
        }
    }//GEN-LAST:event_enrollTeacherRadioButtonItemStateChanged

    private void enrollStudentRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_enrollStudentRadioButtonItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            //change submit button  etc
            MainFrame.setLoginState("enroll-as-student");
            selectFacultyCombo.setVisible(false);
            selectFacultyLabel.setVisible(false);
            firstNameLabel.setVisible(true);
            firstNameTextField.setVisible(true);
            lastNameLabel.setVisible(true);
            lastNameTextField.setVisible(true);
            MainFrame.mainframe.pack();
            submitButton.setText("Enroll as Student");
        }
    }//GEN-LAST:event_enrollStudentRadioButtonItemStateChanged

    private void loginRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginRadioButtonActionPerformed
    
    private void furtherInitComponents() {
        //group radio buttons
        LoginEnrollGroup.add(loginRadioButton);
        LoginEnrollGroup.add(enrollTeacherRadioButton);
        LoginEnrollGroup.add(enrollStudentRadioButton);
        //select defaults(remove dropdown)
        selectFacultyCombo.setVisible(false);
        selectFacultyLabel.setVisible(false);
        firstNameLabel.setVisible(false);
        firstNameTextField.setVisible(false);
        lastNameLabel.setVisible(false);
        lastNameTextField.setVisible(false);
        loginRadioButton.setSelected(true);
        //get list of faculties and add to dropdown
        selectFacultyCombo.setModel(new DefaultComboBoxModel(MainFrame.db.getFaculties().toArray()));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup LoginEnrollGroup;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JRadioButton enrollStudentRadioButton;
    private javax.swing.JRadioButton enrollTeacherRadioButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JRadioButton loginRadioButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JComboBox<String> selectFacultyCombo;
    private javax.swing.JLabel selectFacultyLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables

    private boolean loginEnroll(String selection, String emailUser, String password) {
        switch (selection) {
            case "generic-login":
                return MainFrame.db.tryLogin(emailUser, password);
            case "enroll-as-teacher":
                return MainFrame.db.enrollAsTeacher(emailUser, password, firstNameTextField.getText(), lastNameTextField.getText(), selectFacultyCombo.getSelectedItem().toString());
            case "enroll-as-student":
                return MainFrame.db.enrollAsStudent(emailUser, password, firstNameTextField.getText(), lastNameTextField.getText());
            default:
                ErrorPopup.showMessage(true, "Not A Login Type", "how in middle-earth did we get here");
        }
        return false;
    }
}
