/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NicholasEruba.vgc;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Nicholas
 */
public class LoginEnrollPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginEnrollPanel
     */
    public LoginEnrollPanel() {
        initComponents();
        furtherInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginEnrollGroup = new javax.swing.ButtonGroup();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        enrollTeacherRadioButton = new javax.swing.JRadioButton();
        enrollStudentRadioButton = new javax.swing.JRadioButton();
        selectFacultyCombo = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        loginRadioButton = new javax.swing.JRadioButton();
        selectFacultyLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Login/Enroll"));

        emailLabel.setText("E-mail");

        emailTextField.setText("insert email here");
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        passwordLabel.setText("Password");

        passwordTextField.setText("password");

        enrollTeacherRadioButton.setText("Enroll as teacher");
        enrollTeacherRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                enrollTeacherRadioButtonItemStateChanged(evt);
            }
        });

        enrollStudentRadioButton.setText("Enroll as student");
        enrollStudentRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                enrollStudentRadioButtonItemStateChanged(evt);
            }
        });

        selectFacultyCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectFacultyCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFacultyComboActionPerformed(evt);
            }
        });

        submitButton.setText("Login");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        loginRadioButton.setText("login");
        loginRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                loginRadioButtonItemStateChanged(evt);
            }
        });

        selectFacultyLabel.setText("Select Faculty");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(emailLabel))
                            .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(selectFacultyLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectFacultyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginRadioButton)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enrollTeacherRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enrollStudentRadioButton)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectFacultyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFacultyLabel))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrollTeacherRadioButton)
                    .addComponent(loginRadioButton)
                    .addComponent(enrollStudentRadioButton))
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void selectFacultyComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFacultyComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFacultyComboActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        MainFrame.setPane(new RolesPanel());
    }//GEN-LAST:event_submitButtonActionPerformed

    private void loginRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_loginRadioButtonItemStateChanged
        // TODO add your handling code here:
          if (evt.getStateChange() == ItemEvent.SELECTED) {
        //change submit button  etc
        MainFrame.setLoginState("login-as-any");
        selectFacultyCombo.setVisible(false);
        selectFacultyLabel.setVisible(false);
        submitButton.setText("Login");
    }
    }//GEN-LAST:event_loginRadioButtonItemStateChanged

    private void enrollTeacherRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_enrollTeacherRadioButtonItemStateChanged
        // TODO add your handling code here:
          if (evt.getStateChange() == ItemEvent.SELECTED) {
        //change submit button  etc
        MainFrame.setLoginState("enroll-as-teacher");
        selectFacultyCombo.setVisible(true);
        selectFacultyLabel.setVisible(true);
        submitButton.setText("Enroll as Teacher");
    }
    }//GEN-LAST:event_enrollTeacherRadioButtonItemStateChanged

    private void enrollStudentRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_enrollStudentRadioButtonItemStateChanged
        // TODO add your handling code here:
         if (evt.getStateChange() == ItemEvent.SELECTED) {
        //change submit button  etc
        MainFrame.setLoginState("enroll-as-student");
        selectFacultyCombo.setVisible(false);
        selectFacultyLabel.setVisible(false);
        submitButton.setText("Enroll as Student");
         }
    }//GEN-LAST:event_enrollStudentRadioButtonItemStateChanged

    
    private void furtherInitComponents(){
        //group radio buttons
        LoginEnrollGroup.add(loginRadioButton);
        LoginEnrollGroup.add(enrollTeacherRadioButton);
        LoginEnrollGroup.add(enrollStudentRadioButton);
        //select defaults(remove dropdown)
        selectFacultyCombo.setVisible(false);
        selectFacultyLabel.setVisible(false);
        loginRadioButton.setSelected(true);
        //get list of faculties and add to dropdown
        selectFacultyCombo.setModel(new DefaultComboBoxModel(MainFrame.db.getFaculties().toArray()));
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup LoginEnrollGroup;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JRadioButton enrollStudentRadioButton;
    private javax.swing.JRadioButton enrollTeacherRadioButton;
    private javax.swing.JRadioButton loginRadioButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JComboBox<String> selectFacultyCombo;
    private javax.swing.JLabel selectFacultyLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
